[package]
name = "ex1-simple-microservice"
version = "0.1.0"
edition = "2024"

[features]
ssr = []

[dependencies]
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }